tms/project/urls.py
from django.conf.urls import url ,include
from project import views

#application namespace
app_name = 'ns-project'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.


    # The home page
    url(r'^dashboard/$', views.Dashboard, name='dashboard'),
    url(r'^$', views.Dashboard, name='index'),
    url(r'^$', views.Dashboard, name='dashboard'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^add_project/$', views.AddProject, name='add-project'),
    url(r'^project_list/$', views.ProjectList, name='project-list'),
     url(r'^project_list/(?P<project_status>\w+)$', views.ProjectList, name='project-list'),
    url(r'^project_detail/(?P<pk>\d+)$', views.ProjectDetail, name='project-detail'),
    url(r'^project_edit/(?P<pk>\d+)$', views.ProjectEdit, name='project-edit'),
    url(r'^project_delete/(?P<pk>\d+)$', views.ProjectDelete, name='project-delete'),
    url(r'^task_list_external/(?P<task_status>\w+)$', views.TaskListExternal, name='task-list-external'),
    url(r'^project_task/(?P<pk>\d+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task/(?P<pk>\d+)/(?P<task_status>\w+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task_detail/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskDetail, name='project-task-detail'),

    url(r'^task_update_start/(?P<pk>\d+)$', views.updateStartDate, name='task-update-start'),
    url(r'^update_finish_task/(?P<pk>\d+)$',views.updateTaskFinish, name='update-finish-task'),
    url(r'^update_close_task/(?P<pk>\d+)$',views.updateTaskClose, name='update-close-task'),
    url(r'^update_cancel_task/(?P<pk>\d+)$',views.updateTaskCancel, name='update-cancel-task'),
    url(r'^update_pause_task/(?P<pk>\d+)$',views.updateTaskPause, name='update-pause-task'),
    url(r'^update_assignto_task/(?P<pk>\d+)$',views.updateTaskAssignto, name='update-assignto-task'),
    url(r'^update_assignto_task/(?P<pk>\d+)/(?P<save>\w+)$',views.updateTaskAssignto, name='update-assignto-task'),
    url(r'^update_progress_task/(?P<pk>\d+)$',views.updateTaskProgress, name='update-progress-task'),
    url(r'^project_gantt/(?P<pk>\d+)$',views.ganttChart, name='project-gantt'),
    url(r'^kanban/(?P<pk>\d+)$',views.Kanban, name='kanban'),
    url(r'^project_follow_up/$',views.projectFlowUp, name='project-follow-up'),
    url(r'^project_task_delete/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskDelete, name='project-task-delete'),
    url(r'^project_task_edit/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskEdit, name='project-task-edit'),
    url(r'^project/(?P<project_id>\d+)/team$',views.ProjectTeam, name='project-team'),
    url(r'^project/(?P<project_id>\d+)/addtask$',views.AddTask, name='add-task'),
    url(r'^project/dashboard_manager$',views.DashboardManager, name='dashboard-manager'),
    url(r'^project/dashboard_pm$',views.DashboardPM, name='dashboard-pm'),
    url(r'^project/dashboard_employee/$',views.DashboardEmployee, name='dashboard-employee'),
    url(r'^project/dashboard_employee/(?P<empid>\d+)/$',views.DashboardEmployee, name='dashboard-employee'),
    url(r'^download/(?P<file_name>.+)$', views.Download, name='download'),
    url(r'^email/$', views.senmail, name='email'),
    url(r'^project_report/$', views.ProjectReport, name='project-report'),
    url(r'^project_report/(?P<selectedDpt>.+)$', views.ProjectReport, name='project-report'),
    #login from drupal
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', views.loginfromdrupal, name='loginfromdrupal'),
    #main temp
    url(r'^.*\.html', views.gentella_html, name='gentella'),
   
]

tms/tms/urls.py
from django.conf.urls import include, url
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from project import views
import project.forms
import project.views
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.views import logout

admin.site.site_header = _('Project Management System cp')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # app/ -> Genetelella UI and resources
    url(r'^project/', include('project.urls')),
    url(r'^', include('project.urls')),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'project/login.html',
            'authentication_form': project.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^su/', include('django_su.urls')),
    url(r'^accounts/logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    




]

tms/project/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from simple_history.models import HistoricalRecords
from django.core.validators import MaxValueValidator, MinValueValidator

class Department(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True, unique=True)  # Field name made lowercase.
    managerid = models.CharField(db_column='ManagerId', max_length=45, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.IntegerField(db_column='DeptCode', unique=True, blank=True, null=True)  # Field name made lowercase.
    managername = models.CharField(db_column='ManagerName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    
    class Meta:
        managed = False
        db_table = 'department'

class Employee(models.Model):
    empid = models.IntegerField(db_column='EmpId', unique=True)  # Field name made lowercase.
    empname = models.CharField(db_column='EmpName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.CharField(db_column='DeptCode', max_length=45, blank=True, null=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
    ismanager = models.IntegerField(db_column='IsManager', blank=True, null=True)  # Field name made lowercase.
    ext = models.CharField(db_column='Ext', max_length=45, blank=True, null=True)  # Field name made lowercase.
    mobile = models.CharField(db_column='Mobile', max_length=45, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
    jobtitle = models.CharField(db_column='JobTitle', max_length=200, blank=True, null=True)  # Field name made lowercase.
    managercode = models.BigIntegerField(db_column='ManagerCode', blank=True, null=True)  # Field name made lowercase.
    sexcode = models.CharField(db_column='SexCode', max_length=6, blank=True, null=True)  # Field name made lowercase.
    iscontract = models.IntegerField(db_column='IsContract', blank=True, null=True)  # Field name made lowercase.


    class Meta:
        managed = False
        db_table = 'employee'

class Project(models.Model):
    name = models.CharField(db_column='Name', max_length=250)  # Field name made lowercase.
    start = models.DateField(db_column='Start')  # Field name made lowercase.
    end = models.DateField(db_column='End')
    teamname = models.CharField(db_column='TeamName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    desc = models.CharField(db_column='Desc', max_length=1500)  # Field name made lowercase.
    #createdby = models.CharField(db_column='CreatedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    createdby = models.ForeignKey('Employee',db_column='createdby',to_field='empid',related_name='Employee_createdby',on_delete=models.SET_NULL, blank=True, null=True)

    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    departement = models.ForeignKey('Department',db_column='DepartementId', to_field='deptcode',on_delete=models.SET_NULL, blank=True, null=True)
    #statusid = models.IntegerField(db_column='StatusId', blank=True, null=True)  # Field name made lowercase.
    status = models.ForeignKey('ProjectStatus', on_delete=models.SET_NULL, null=True)
    openedby = models.CharField(db_column='OpenedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    openeddate = models.DateTimeField(db_column='OpenedDate', blank=True, null=True)  # Field name made lowercase.
    closedby = models.CharField(db_column='ClosedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    closeddate = models.DateTimeField(db_column='ClosedDate', blank=True, null=True)  # Field name made lowercase.
    canceledby = models.CharField(db_column='CanceledBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    canceleddate = models.DateTimeField(db_column='CanceledDate', blank=True, null=True)  # Field name made lowercase.
    deleted = models.IntegerField(db_column='Deleted', blank=True, null=True)  # Field name made lowercase.
    lasteditby = models.ForeignKey('Employee',db_column='LastEditBy',to_field='empid',related_name='Project_Employee_LastEditBy',on_delete=models.SET_NULL, blank=True, null=True)
    delegationto = models.ForeignKey('Employee',db_column='DelegationTo',to_field='empid',related_name='Project_Employee_DelegationTo',on_delete=models.SET_NULL, blank=True, null=True)
    delegationdate= models.DateTimeField(db_column='DelegationDate', blank=True, null=True) 
    class Meta:
        managed = False
        db_table = 'project'

class ProjectStatus(models.Model):
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    name_ar = models.CharField(db_column='Name_Ar', max_length=10)  # Field name made lowercase.
    priority = models.IntegerField(db_column='Priority')  # Field name made lowercase.
    isdefault = models.IntegerField(db_column='IsDefault')  # Field name made lowercase.
    color = models.CharField(db_column='Color', max_length=10)  # Field name made lowercase.

    def __str__(self):
        return self.name_ar
        self.fields['verb'].empty_label = 'None'

    class Meta:
        managed = False
        db_table = 'project_status'

class Sheet(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    empid = models.BigIntegerField(db_column='EmpId', blank=True, null=True)  # Field name made lowercase.
    deptcode = models.IntegerField(db_column='DeptCode', blank=True, null=True)  # Field name made lowercase.
    managercode = models.BigIntegerField(db_column='ManagerCode', blank=True, null=True)  # Field name made lowercase.
    managerlevel2 = models.BigIntegerField(db_column='ManagerLevel2', blank=True, null=True)  # Field name made lowercase.
    managerlevel3 = models.BigIntegerField(db_column='ManagerLevel3', blank=True, null=True)  # Field name made lowercase.
    managerlevel4 = models.BigIntegerField(db_column='ManagerLevel4', blank=True, null=True)  # Field name made lowercase.
    taskdesc = models.CharField(_('Task Descreption'),db_column='TaskDesc', max_length=255, blank=True, null=True)  # Field name made lowercase.
    TASK_STATUS = (
        ('', _('Choice type')),
        ('m', _('Master')),
        ('h', _('Help')),
    )
    tasktype = models.CharField(_('Task type'), max_length=1, choices=TASK_STATUS, db_column='TaskType', blank=True, null=True)  # Field name made lowercase.
    duration = models.IntegerField(_('Duration'),db_column='Duration',blank=True, null=True)  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    taskdate = models.DateField(_('task date'),db_column='TaskDate', blank=False, null=False)  # Field name made lowercase.
    editedate = models.DateTimeField(db_column='EditeDate', blank=True, null=True)  # Field name made lowercase.
    SUBMITTED_STATUS = (
        ('', _('Choice action')),
        ('0', _('New')),
        ('1', _('submitted')),
        ('2', _('not submitted')),
    )
    ifsubmitted = models.CharField(db_column='IfSubmitted',max_length=1,choices=SUBMITTED_STATUS, blank=True, null=True)  # Field name made lowercase.
    SHEET_STATUS = (
        ('', _('Choice status')),
        ('0', _('New')),
        ('1', _('in progres')),
        ('2', _('Done')),
        ('3', _('Ignore')),
    )
    status = models.CharField(db_column='Status',choices=SHEET_STATUS, max_length=1)  # Field name made lowercase.
    statusdate = models.DateTimeField(db_column='StatusDate', blank=True, null=True)  # Field name made lowercase.
    REASON_STATUS = (
        ('', _('Choice reason')),
        ('0', _('Need Support')),
        ('1', _('Change piroty')),
    )
    reason = models.CharField(db_column='Reason',choices=REASON_STATUS, max_length=1,blank=True, null=True)  # Field name made lowercase.
    submittedby = models.IntegerField(db_column='SubmittedBy', blank=True, null=True)  # Field name made lowercase.
    submitteddate = models.DateTimeField(db_column='SubmittedDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sheet'

class VSheetsdata(models.Model):
    id = models.IntegerField(db_column='Id',primary_key=True)  # Field name made lowercase.
    employeeid = models.CharField(db_column='EmployeeId', max_length=45, blank=True, null=True)  # Field name made lowercase.
    employeename = models.CharField(db_column='EmployeeName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.CharField(db_column='DeptCode', max_length=45, blank=True, null=True)  # Field name made lowercase.
    managername = models.CharField(db_column='ManagerName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    totaltask = models.BigIntegerField(db_column='TotalTask')  # Field name made lowercase.
    notsubmitted = models.BigIntegerField(db_column='NotSubmitted', blank=True, null=True)  # Field name made lowercase.
    submitted = models.BigIntegerField(db_column='Submitted', blank=True, null=True)  # Field name made lowercase.
    new = models.BigIntegerField(db_column='New', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'V_SheetsData'

class VDeptsheetsdata(models.Model):

tms/project/templates/project/details_sheets.html
{% extends "project/base_site.html" %}
{% load i18n %}
{% block title %} {% trans "sheets list" %} {% endblock title %}

{% block stylesheets %}
{{ block.super }}
<link href="/static/vendors/jquery/dist/jquery-ui.css" rel="stylesheet">
{% endblock stylesheets %}
{% block content %}
  <div class="right_col" role="main">
    <div class="row">
      <div class="col-md-12">
        <div class="x_panel">
          <div class="x_title">
            <h2 style="font-size:20px; line-height:1.5em;">{{ _('Employee Details')}} </h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <section class="content invoice">
              <!-- title row -->
              <div class="row">
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  {% for data in EmpData %}
              <address style="font-size: 17px;">
                <br>
                <b>{{ _('Name')}}:</b> {{ data.empname}}
                <br>
                <br>
                <b>{{ _('Department')}}:</b> {{ data.deptname}}
                <br>
                <br>
                 <b>{{ _('Job title')}}:</b> {{ data.jobtitle}}
              </address>
                </div>
                <div class="col-sm-4 invoice-col"style="font-size: 17px;">
                  <br>
                  <b>{{ _('Mobile')}}:</b> {{ data.mobile}}
                  <br>
                  <br>
                   <b>{{ _('Ext')}}:</b> {{ data.ext}}
                  <br>
                  <br>
                   <b>{{ _('Email')}}:</b> {{ data.email}}
                </div>
                {% endfor %}
                <!-- /.col -->
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
    <div class="">
      <!--  <div class="page-title">
        <div class="title_left">
        <h3>{% trans "submitted tasks" %} </h3>
        </div>
      </div>-->
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_content">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{{ _('Task Descreption') }}</th>
        <th>{{ _('Task type') }}</th>
        <th>{{ _('Duration') }}</th>
       <th>{{ _('Task Date') }}</th>
       <th>{{ _('Submitted') }} </th>
      </tr>
    </thead>
    <tbody>
      {% for form in allsheet %}

      <tr>
        <td>{{ form.taskdesc }}
          {{ taskdesc }}
          {{ form.get_taskdesc_display }}
        </td>
        <td>
        {{ form.get_tasktype_display }}
        </td>
        <td class="col-md-2"> {{ form.duration }}</td>
        <td class="col-md-2"> {{ form.taskdate }} </td>
          </div>
         </div>
        </td>

        <td>
          {{ form.get_ifsubmitted_display }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
<script>


</script>
{% block javascripts %}

  {{ block.super }}
{% endblock javascripts %}

tms/project/templates/project/fixed_footer.html
{% extends "project/base_site.html" %}

{% block title %} Fixed Footer {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <link href="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
{% endblock stylesheets %}

{% block body_class %}nav-md footer_fixed{% endblock body_class %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Fixed Footer <small> Just add class <strong>footer_fixed</strong></small></h3>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- jQuery custom content scroller -->
  <script src="/static/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock javascripts %}

tms/project/templates/project/kanban.html
{% extends "project/base_site.html" %}
{% load i18n %}
{% block title %} Plain Page {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
      <div class="">
       
      <!-- top menu bar -->
{% include "project/project_nave.html" %}



     

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
     <div class="x_title">

              <h2>{% trans "Knaban" %}  </h2>
                 <ul class="nav navbar-right panel_toolbox">
                                    <a href="{{request.META.HTTP_REFERER}}" >  <button type="button" class="btn btn-primary">{{ _('Back')}} <i class="fa fa-angle-double-left"></i> </button></a>
                  
                  </ul>
                  <div class="clearfix"></div>
              </div>
             
                <div class="x_content">
                          <div class="col-md-12 col-sm-12 col-xs-12">

            

<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#5bc0de;color:#fff;">
<div><h4>{% trans "New" %} ({{ new_tasks|length }})</h4></div>
{% for task in new_tasks%}  
<div class="tile-stats p-kanban"  >
<div style="padding:10px;" >
<span class="label label-info" style="margin-left: 5px;">{{task.get_status_display }} </span>
{{ task.name|truncatewords:5 }}
 </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i>{{ task.assignedto.empname|truncatewords:5 }} {{task.departement.name|truncatewords:5}} </div>
</div>
{% endfor %}
</div>

<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#337ab7;color:#fff;">
<div><h4>{% trans "Inprogress" %} ({{ inprogress_tasks|length }})</h4></div>
{% for task in inprogress_tasks%}  
<div class="tile-stats p-kanban"  >
<div style="padding:10px;" ><span class="label label-primary" style="margin-left: 5px;">{{task.get_status_display }} </span>{{task.name}} </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i> {{ task.assignedto.empname}}{{task.assignto.empname}}{{task.departement.name}} </div>
</div>



{% endfor %}
</div>

<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#5cb85c;color:#fff;">
<div><h4>{% trans "Done" %} ({{ done_tasks|length }}) </h4></div>
{% for task in done_tasks%} 
<div class="tile-stats p-kanban" >
<div style="padding:10px;" ><span class="label label-success" style="margin-left: 5px;">{{task.get_status_display }} </span>{{task.name}} </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i> {{ task.assignedto.empname}}{{task.assignto.empname}}{{task.departement.name}} </div>
</div>
{% endfor %}
</div>


<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#f0ad4e;color:#fff;">
<div><h4>{% trans "Hold" %} ({{ hold_tasks|length }}) </h4></div>
{% for task in hold_tasks%} 
<div class="tile-stats p-kanban"  >
<div style="padding:10px;" ><span class="label label-warning" style="margin-left: 5px;">{{task.get_status_display }} </span>{{task.name}} </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i> {{ task.assignedto.empname}}{{task.assignto.empname}}{{task.departement.name}} </div>
</div>
{% endfor %}
</div>


<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#d9534f;color:#fff;">
<div><h4 >{% trans "Cancelled" %} ({{ cancelled_tasks|length }}) </h4> </div>
{% for task in cancelled_tasks%} 
<div class="tile-stats p-kanban" >
<div style="padding:10px;" ><span class="label label-danger" style="margin-left: 5px;">{{task.get_status_display }} </span>{{task.name}} </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i> {{ task.assignedto.empname}}{{task.assignto.empname}}{{task.departement.name}} </div>
</div>
{% endfor %}
</div>


<div class="col-md-2 col-sm-12 col-xs-12 task-card" style="background:#a8b1b9;color:#fff;">
<div><h4>{% trans "Closed" %} ({{ closed_tasks|length }}) </h4></div>
{% for task in closed_tasks %}
<div class="tile-stats p-kanban" style="border-color: #777;" >
<div style="padding:10px;" ><span class="badge badge-success" style="margin-left: 5px;">{{task.get_status_display }} </span>{{task.name}} </div>
 <div class="clearfix" style="border-bottom: #e4e4e4 solid 1px;"></div>
<div style="padding:10px;" ><div class="task_number" style="padding:1px;">{{ task.id}}</div><i class="fa fa-hand-o-left text-default" title="مهام مسندة لى  "></i> {{ task.assignedto.empname}}{{task.assignto.empname}}{{task.departement.name}} </div>
</div>

{% endfor %}
</div>


               
            </div>
            
       </div>
       
        </div>
      </div>
    </div>
    
    
      </div>
</div>

{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  
  
{% endblock javascripts %}

tms/project/templates/project/top_navigation.html
{% load i18n %}
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="/static/images/user.png" alt="">
          {% if user.is_authenticated %}
            {% if 'EmpName' in request.session %}
            {{ request.session.EmpName }}
            {# {{ mail }}#}
            {% endif %}
            {% endif %}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
  
          <li><a href="{% url 'ns-project:dashboard-employee' request.session.EmpID %}">{{ _('Profile')}} </a></li>  
          <li><a href="{% url 'logout'%}"><i class="fa fa-sign-out pull-right"></i>{{ _('Log Out')}} </a></li>
        </ul>
      </li>

    </ul>
  </nav>
</div>