tms/project/urls.py
from django.conf.urls import url ,include
from project import views

#application namespace
app_name = 'ns-project'

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.


    # The home page
    url(r'^dashboard/$', views.Dashboard, name='dashboard'),
    url(r'^$', views.Dashboard, name='index'),
    url(r'^$', views.Dashboard, name='dashboard'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^add_project/$', views.AddProject, name='add-project'),
    url(r'^project_list/$', views.ProjectList, name='project-list'),
     url(r'^project_list/(?P<project_status>\w+)$', views.ProjectList, name='project-list'),
    url(r'^project_detail/(?P<pk>\d+)$', views.ProjectDetail, name='project-detail'),
    url(r'^project_edit/(?P<pk>\d+)$', views.ProjectEdit, name='project-edit'),
    url(r'^project_delete/(?P<pk>\d+)$', views.ProjectDelete, name='project-delete'),
    url(r'^task_list_external/(?P<task_status>\w+)$', views.TaskListExternal, name='task-list-external'),
    url(r'^project_task/(?P<pk>\d+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task/(?P<pk>\d+)/(?P<task_status>\w+)$', views.ProjectTask, name='project-task'),
    url(r'^project_task_detail/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskDetail, name='project-task-detail'),

    url(r'^task_update_start/(?P<pk>\d+)$', views.updateStartDate, name='task-update-start'),
    url(r'^update_finish_task/(?P<pk>\d+)$',views.updateTaskFinish, name='update-finish-task'),
    url(r'^update_close_task/(?P<pk>\d+)$',views.updateTaskClose, name='update-close-task'),
    url(r'^update_cancel_task/(?P<pk>\d+)$',views.updateTaskCancel, name='update-cancel-task'),
    url(r'^update_pause_task/(?P<pk>\d+)$',views.updateTaskPause, name='update-pause-task'),
    url(r'^update_assignto_task/(?P<pk>\d+)$',views.updateTaskAssignto, name='update-assignto-task'),
    url(r'^update_assignto_task/(?P<pk>\d+)/(?P<save>\w+)$',views.updateTaskAssignto, name='update-assignto-task'),
    url(r'^update_progress_task/(?P<pk>\d+)$',views.updateTaskProgress, name='update-progress-task'),
    url(r'^project_gantt/(?P<pk>\d+)$',views.ganttChart, name='project-gantt'),
    url(r'^kanban/(?P<pk>\d+)$',views.Kanban, name='kanban'),
    url(r'^project_follow_up/$',views.projectFlowUp, name='project-follow-up'),
    url(r'^project_task_delete/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskDelete, name='project-task-delete'),
    url(r'^project_task_edit/(?P<projectid>\d+)/(?P<taskid>\d+)$', views.ProjectTaskEdit, name='project-task-edit'),
    url(r'^project/(?P<project_id>\d+)/team$',views.ProjectTeam, name='project-team'),
    url(r'^project/(?P<project_id>\d+)/addtask$',views.AddTask, name='add-task'),
    url(r'^project/dashboard_manager$',views.DashboardManager, name='dashboard-manager'),
    url(r'^project/dashboard_pm$',views.DashboardPM, name='dashboard-pm'),
    url(r'^project/dashboard_employee/$',views.DashboardEmployee, name='dashboard-employee'),
    url(r'^project/dashboard_employee/(?P<empid>\d+)/$',views.DashboardEmployee, name='dashboard-employee'),
    url(r'^download/(?P<file_name>.+)$', views.Download, name='download'),
    url(r'^email/$', views.senmail, name='email'),
    url(r'^project_report/$', views.ProjectReport, name='project-report'),
    url(r'^project_report/(?P<selectedDpt>.+)$', views.ProjectReport, name='project-report'),
    #login from drupal
    url(r'^auth/(?P<email>.*)/(?P<signature>.*)/(?P<time>.*)/$', views.loginfromdrupal, name='loginfromdrupal'),
    #main temp
    url(r'^.*\.html', views.gentella_html, name='gentella'),
   
]

tms/tms/urls.py
from django.conf.urls import include, url
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from project import views
import project.forms
import project.views
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.views import logout

admin.site.site_header = _('Project Management System cp')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # app/ -> Genetelella UI and resources
    url(r'^project/', include('project.urls')),
    url(r'^', include('project.urls')),
    url(r'^accounts/login/$',
        views.myuser,
        {
            'template_name': 'project/login.html',
            'authentication_form': project.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^su/', include('django_su.urls')),
    url(r'^accounts/logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    




]

tms/project/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from simple_history.models import HistoricalRecords
from django.core.validators import MaxValueValidator, MinValueValidator

class Department(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True, unique=True)  # Field name made lowercase.
    managerid = models.CharField(db_column='ManagerId', max_length=45, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.IntegerField(db_column='DeptCode', unique=True, blank=True, null=True)  # Field name made lowercase.
    managername = models.CharField(db_column='ManagerName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    
    class Meta:
        managed = False
        db_table = 'department'

class Employee(models.Model):
    empid = models.IntegerField(db_column='EmpId', unique=True)  # Field name made lowercase.
    empname = models.CharField(db_column='EmpName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.CharField(db_column='DeptCode', max_length=45, blank=True, null=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
    ismanager = models.IntegerField(db_column='IsManager', blank=True, null=True)  # Field name made lowercase.
    ext = models.CharField(db_column='Ext', max_length=45, blank=True, null=True)  # Field name made lowercase.
    mobile = models.CharField(db_column='Mobile', max_length=45, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
    jobtitle = models.CharField(db_column='JobTitle', max_length=200, blank=True, null=True)  # Field name made lowercase.
    managercode = models.BigIntegerField(db_column='ManagerCode', blank=True, null=True)  # Field name made lowercase.
    sexcode = models.CharField(db_column='SexCode', max_length=6, blank=True, null=True)  # Field name made lowercase.
    iscontract = models.IntegerField(db_column='IsContract', blank=True, null=True)  # Field name made lowercase.


    class Meta:
        managed = False
        db_table = 'employee'

class Project(models.Model):
    name = models.CharField(db_column='Name', max_length=250)  # Field name made lowercase.
    start = models.DateField(db_column='Start')  # Field name made lowercase.
    end = models.DateField(db_column='End')
    teamname = models.CharField(db_column='TeamName', max_length=100, blank=True, null=True)  # Field name made lowercase.
    desc = models.CharField(db_column='Desc', max_length=1500)  # Field name made lowercase.
    #createdby = models.CharField(db_column='CreatedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    createdby = models.ForeignKey('Employee',db_column='createdby',to_field='empid',related_name='Employee_createdby',on_delete=models.SET_NULL, blank=True, null=True)

    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    departement = models.ForeignKey('Department',db_column='DepartementId', to_field='deptcode',on_delete=models.SET_NULL, blank=True, null=True)
    #statusid = models.IntegerField(db_column='StatusId', blank=True, null=True)  # Field name made lowercase.
    status = models.ForeignKey('ProjectStatus', on_delete=models.SET_NULL, null=True)
    openedby = models.CharField(db_column='OpenedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    openeddate = models.DateTimeField(db_column='OpenedDate', blank=True, null=True)  # Field name made lowercase.
    closedby = models.CharField(db_column='ClosedBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    closeddate = models.DateTimeField(db_column='ClosedDate', blank=True, null=True)  # Field name made lowercase.
    canceledby = models.CharField(db_column='CanceledBy', max_length=20, blank=True, null=True)  # Field name made lowercase.
    canceleddate = models.DateTimeField(db_column='CanceledDate', blank=True, null=True)  # Field name made lowercase.
    deleted = models.IntegerField(db_column='Deleted', blank=True, null=True)  # Field name made lowercase.
    lasteditby = models.ForeignKey('Employee',db_column='LastEditBy',to_field='empid',related_name='Project_Employee_LastEditBy',on_delete=models.SET_NULL, blank=True, null=True)
    delegationto = models.ForeignKey('Employee',db_column='DelegationTo',to_field='empid',related_name='Project_Employee_DelegationTo',on_delete=models.SET_NULL, blank=True, null=True)
    delegationdate= models.DateTimeField(db_column='DelegationDate', blank=True, null=True) 
    class Meta:
        managed = False
        db_table = 'project'

class ProjectStatus(models.Model):
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    name_ar = models.CharField(db_column='Name_Ar', max_length=10)  # Field name made lowercase.
    priority = models.IntegerField(db_column='Priority')  # Field name made lowercase.
    isdefault = models.IntegerField(db_column='IsDefault')  # Field name made lowercase.
    color = models.CharField(db_column='Color', max_length=10)  # Field name made lowercase.

    def __str__(self):
        return self.name_ar
        self.fields['verb'].empty_label = 'None'

    class Meta:
        managed = False
        db_table = 'project_status'

class Sheet(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    empid = models.BigIntegerField(db_column='EmpId', blank=True, null=True)  # Field name made lowercase.
    deptcode = models.IntegerField(db_column='DeptCode', blank=True, null=True)  # Field name made lowercase.
    managercode = models.BigIntegerField(db_column='ManagerCode', blank=True, null=True)  # Field name made lowercase.
    managerlevel2 = models.BigIntegerField(db_column='ManagerLevel2', blank=True, null=True)  # Field name made lowercase.
    managerlevel3 = models.BigIntegerField(db_column='ManagerLevel3', blank=True, null=True)  # Field name made lowercase.
    managerlevel4 = models.BigIntegerField(db_column='ManagerLevel4', blank=True, null=True)  # Field name made lowercase.
    taskdesc = models.CharField(_('Task Descreption'),db_column='TaskDesc', max_length=255, blank=True, null=True)  # Field name made lowercase.
    TASK_STATUS = (
        ('', _('Choice type')),
        ('m', _('Master')),
        ('h', _('Help')),
    )
    tasktype = models.CharField(_('Task type'), max_length=1, choices=TASK_STATUS, db_column='TaskType', blank=True, null=True)  # Field name made lowercase.
    duration = models.IntegerField(_('Duration'),db_column='Duration',blank=True, null=True)  # Field name made lowercase.
    createddate = models.DateTimeField(db_column='CreatedDate', blank=True, null=True)  # Field name made lowercase.
    taskdate = models.DateField(_('task date'),db_column='TaskDate', blank=False, null=False)  # Field name made lowercase.
    editedate = models.DateTimeField(db_column='EditeDate', blank=True, null=True)  # Field name made lowercase.
    SUBMITTED_STATUS = (
        ('', _('Choice action')),
        ('0', _('New')),
        ('1', _('submitted')),
        ('2', _('not submitted')),
    )
    ifsubmitted = models.CharField(db_column='IfSubmitted',max_length=1,choices=SUBMITTED_STATUS, blank=True, null=True)  # Field name made lowercase.
    SHEET_STATUS = (
        ('', _('Choice status')),
        ('0', _('New')),
        ('1', _('in progres')),
        ('2', _('Done')),
        ('3', _('Ignore')),
    )
    status = models.CharField(db_column='Status',choices=SHEET_STATUS, max_length=1)  # Field name made lowercase.
    statusdate = models.DateTimeField(db_column='StatusDate', blank=True, null=True)  # Field name made lowercase.
    REASON_STATUS = (
        ('', _('Choice reason')),
        ('0', _('Need Support')),
        ('1', _('Change piroty')),
    )
    reason = models.CharField(db_column='Reason',choices=REASON_STATUS, max_length=1,blank=True, null=True)  # Field name made lowercase.
    submittedby = models.IntegerField(db_column='SubmittedBy', blank=True, null=True)  # Field name made lowercase.
    submitteddate = models.DateTimeField(db_column='SubmittedDate', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sheet'

class VSheetsdata(models.Model):
    id = models.IntegerField(db_column='Id',primary_key=True)  # Field name made lowercase.
    employeeid = models.CharField(db_column='EmployeeId', max_length=45, blank=True, null=True)  # Field name made lowercase.
    employeename = models.CharField(db_column='EmployeeName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    deptname = models.CharField(db_column='DeptName', max_length=200, blank=True, null=True)  # Field name made lowercase.
    deptcode = models.CharField(db_column='DeptCode', max_length=45, blank=True, null=True)  # Field name made lowercase.
    managername = models.CharField(db_column='ManagerName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    totaltask = models.BigIntegerField(db_column='TotalTask')  # Field name made lowercase.
    notsubmitted = models.BigIntegerField(db_column='NotSubmitted', blank=True, null=True)  # Field name made lowercase.
    submitted = models.BigIntegerField(db_column='Submitted', blank=True, null=True)  # Field name made lowercase.
    new = models.BigIntegerField(db_column='New', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'V_SheetsData'

class VDeptsheetsdata(models.Model):

tms/project/templates/project/task/update_assignto_task.html
      {% block stylesheets %}

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.2/chosen.css" />
  {% endblock stylesheets %}
  {% load i18n %}
   <form action="/project/update_assignto_task/{{pk}}/{{save}}" method="post" class="form-horizontal form-label-left input_mask update-assignto-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Assign task to" %} </h4>
                  </div>
    <div class="modal-body"> 

  <div class="form-group col-md-8 col-sm-12 col-xs-12 list-inline-item">
               {{form.assigntype.label_tag}}
               {{form.assigntype}}
              </div>
              
     <div class="form-group col-md-8 col-sm-12 col-xs-12">
               {{form.employee.label_tag}}
               {{form.employee}}
              </div>
                <div class="form-group col-md-8 col-sm-12 col-xs-12">
               {{form.departement.label_tag}}
               {{form.departement}}
              </div>
            <div class="Clearfix"></div>
                  <div class="col-md-12 col-sm-12 col-xs-12  Clearfix">    
                <div class="form-group">
               
                {% if errors %}
           
              
              {% for error in errors %}
            <li class="text-danger">  {{ error.as_text }}</li>
           
            {% endfor %}
           
    {% endif %}  
                  </div>
                  


   </div>
   
     <div class="modal-footer col-md-12 col-sm-12 col-xs-12  Clearfix">    
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close"%}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>

{% block javascripts %}

       <script>
     $(".chosen").css("width","100%");
     $(".chosen").data("placeholder","اختر ...").chosen();
     $(".chosen").chosen({no_results_text: "لايوجد بيانات متاحة"}); 
     $('.chosen').chosen({allow_single_deselect: true,no_results_text: "لايوجد بيانات متاحة"});

     // disable /enable droplis
    
       $('#id_assigntype_0').change(function(){
   	   $('#id_employee').prop("disabled", false).trigger("chosen:updated");
       $('#id_departement').prop("disabled", true).trigger("chosen:updated");
   	});
       
       $('#id_assigntype_1').change(function(){
       $('#id_employee').prop("disabled", true).trigger("chosen:updated");
       $('#id_departement').prop("disabled", false).trigger("chosen:updated");
       	});
     
</script>

{% endblock javascripts %}

tms/project/templates/project/task/update_cancel_task.html
  {% load i18n %}
   <form action="/project/update_cancel_task/{{pk}}" method="post" class="form-horizontal form-label-left input_mask update-cancel-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Cancel Task" %} </h4>
                  </div>
    <div class="modal-body"> 

               <div class="form-group">
              <div class=" col-md-12">
               {{form.reason.label_tag}}
               {{form.reason}}
              </div>
              </div>
                                  
                <div class="form-group">
           
                {% if errors %}
        <ul>
            {% for error in errors %}
            <li class="text-danger">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
                 
                  </div>
                  


   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



  <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>

tms/project/templates/project/task/update_close_task.html
   {% load i18n %}
     <form action="/project/update_close_task/{{pk}}" method="post" class="form-horizontal form-label-left input_mask update-close-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Close Task" %} </h4>
                  </div>
    <div class="modal-body"> 

               
               
               <div class="form-group">
              <div class=" col-md-12">
               {{form.reason.label_tag}}
               {{form.reason}}
              </div>
              </div>
                                  
                <div class="form-group">
           
                {% if errors %}
        <ul>
            {% for error in errors %}
            <li class="text-danger">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
                 
                  </div>
                  


   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



  <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>

tms/project/templates/project/task/update_finish_task.html
  {% load i18n %}
     <form action="/project/update_finish_task/{{pk}}" method="post" class="form-horizontal form-label-left input_mask update-finish-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Task Finish" %} </h4>
                  </div>
    <div class="modal-body"> 

      <div class="form-group">
              <div class=" col-md-4">
              {{form.ftime.label_tag}}
               {{form.ftime}}
                <span class="fa fa-calendar-o form-control-feedback left" style="margin-top:25px;" aria-hidden="true"></span>
               </div>
               </div>
               
               
               <div class="form-group">
              <div class=" col-md-12">
               {{form.notes.label_tag}}
               {{form.notes}}
              </div>
              </div>
              
                <div class="form-group">
                  {{ form.ftime.errors }}
                  {{ form.notes.errors }}
                  </div>

   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



    <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>

tms/project/templates/project/task/update_pause_task.html
  {% load i18n %}
   <form action="/project/update_pause_task/{{pk}}" method="post" class="form-horizontal form-label-left input_mask update-pause-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Pause Task" %} </h4>
                  </div>
    <div class="modal-body"> 

               <div class="form-group">
              <div class=" col-md-12">
               {{form.note.label_tag}}
               {{form.note}}
              </div>
              </div>
                                  
                <div class="form-group">
           
                {% if errors %}
        <ul>
            {% for error in errors %}
            <li class="text-danger">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
                 
                  </div>
                  


   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



  <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>

tms/project/templates/project/task/update_progress_task.html
   {% load i18n %}
     <form action="/project/update_progress_task/{{pk}}" method="post" class="form-horizontal form-label-left input_mask update-progress-task-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Progress" %} </h4>
                  </div>
    <div class="modal-body"> 

                 <div class="form-group">
              <div class=" col-md-12" style="position:relative">
               {{form.progress.label_tag}}
               {{form.progress}} <i class="fa fa-percent" aria-hidden="true" ></i>

              </div>
              </div>
               
               <div class="form-group">
              <div class=" col-md-12">
               {{form.note.label_tag}}
               {{form.note}}
              </div>
              </div>
                                  
                <div class="form-group">
           
                {% if errors %}
        <div  class="text-danger">
            {% for error in errors %}
         {{ error }}
            {% endfor %}
  </div>
    {% endif %}
    
                 
                  </div>
                  


   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



  <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>

tms/project/templates/project/task/update_start_task.html
  {% load i18n %}
     <form action="/project/task_update_start/{{pk}}" method="post" class="form-horizontal form-label-left input_mask task-update-start-form" novalidate enctype="multipart/form-data">

  {% csrf_token %}
     <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">x</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Task Start" %} </h4>
                  </div>
    <div class="modal-body"> 

      <div class="form-group">
              <div class=" col-md-4">
              {{form.rsd.label_tag}}
               {{form.rsd}}
                <span class="fa fa-calendar-o form-control-feedback left" style="margin-top:25px;" aria-hidden="true"></span>
               </div>
               </div>
               
               
                 <div class="form-group">
              <div class=" col-md-12">
               {{form.notes.label_tag}}
               {{form.notes}}
              </div>
              </div>
              
                <div class="form-group">
                  {{ form.rsd.errors }}
                  {{ form.notes.errors }}
                  </div>

   </div>
   
     <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                    <button type="submit" class="btn btn-primary">{% trans "Save changes" %}</button>
        </div>          
    </form>



    <script>
  $('#single_cal_1').daterangepicker({
      singleDatePicker: true,
      singleClasses: "picker_1",
       locale: {
            format: 'YYYY-MM-DD'
        },
  }, function(start, end, label) {
     
  }); 
   </script>